apiVersion: v1
kind: Pod
metadata:
  name: minio-clinet
spec:
  containers:
  - name: minio-clinet
    image: minio/mc
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always