apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}-secret
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.secrets.htpasswd }}
  htpasswd: {{ .Values.secrets.htpasswd | b64enc }}
  {{- end }}
  {{- if .Values.secrets.haSharedSecret }}
  haSharedSecret: {{ .Values.secrets.haSharedSecret | b64enc | quote }}
  {{- else }}
  haSharedSecret: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}