{% for service_name in stateful_services %}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ service_name }}-{{ namespace }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{% endfor %}

{% for volume in helper_volumes %}
{% for node in groups.k8s_workers | sort %}
{% set node_index = loop.index %}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ volume.name }}-{{ namespace }}-{{ node_index }}
spec:
  storageClassName: {{ volume.belong_to_service }}-{{ namespace }}
  capacity:
    storage: {{ volume.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/pv-{{ volume.name }}-{{ namespace }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ node }}
{% endfor %}
{% endfor %}
